### ISSUE TITLE
Wikis erased when they're not present in WikimediaMessages file

### ISSUE THREAD

**Issue by bearloga** [wikimedia-research/canonical-data#1]
@kcvelaga asked me about the omission of [Doteli Wikipedia](https://dty.wikipedia.org/wiki/%E0%A4%AE%E0%A5%81%E0%A4%96%E0%A5%8D%E0%A4%AF_%E0%A4%AA%E0%A4%A8%E0%A5%8D%E0%A4%A8%E0%A4%BE) (dtywiki) and [Punjabi Wikisource](https://pa.wikisource.org/wiki/%E0%A8%AE%E0%A9%81%E0%A9%B1%E0%A8%96_%E0%A8%B8%E0%A8%AB%E0%A8%BC%E0%A8%BE) (pawikisource).

- Those are missing in [Extension:WikimediaMessages](https://www.mediawiki.org/wiki/Extension:WikimediaMessages)'s [i18n/wikimediaprojectnames/en.json](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikimediaMessages/+/refs/heads/master/i18n/wikimediaprojectnames/en.json)
- The second-to-last cell uses [DataFrame.merge](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html):
  ```python
  wikis = wikis.merge(project_names, on="database_code")
  ```
  which by default performs an _inner_ join rather than a _left_ or _outer_ join, so dtywiki and pawikisource – which are both in wikis up until then – are both erased at that point thanks to their omission from `project_names`

Maybe we could try a different approach by switching to the [SiteMatrix API](https://www.mediawiki.org/wiki/Extension:SiteMatrix#API) which returns entries like:

```json
{
    "code": "dty",
    "name": "\u0921\u094b\u091f\u0947\u0932\u0940",
    "site": [
        {
            "url": "https://dty.wikipedia.org",
            "dbname": "dtywiki",
            "code": "wiki",
            "sitename": "\u0935\u093f\u0915\u093f\u092a\u093f\u0921\u093f\u092f\u093e"
        }
    ],
    "dir": "ltr",
    "localname": "Doteli"
}
```

**Comment by nettrom** [comment]
I've investigated using the SiteMatrix API for this, and it comes with its own set of issues. The data returned by the API appears tailor made to create the tables shown on for example [mw:Special:SiteMatrix](https://www.mediawiki.org/wiki/Special:SiteMatrix). Each row in the first table is a language, and each column is a wiki, which is how the data is organized. We do not get English project names from this and so would have to map those (e.g. `wiki` to `Wikipedia`) to get the full name. The API also handles additional wikis (e.g. chapter wikis) as "specials" and do not contain any localization of their names, so we would still have to get those from a different place.

I think the way to move forward on this is to:

1. Change the `project_names` merge to a left join.
2. Add project names manually for wikis that are missing after the join similarly to what we do with `language_name`.

I'll create a pull request to take care of that. I'll also follow up internally to learn what options we have when it comes to canonical sources for English project names.

**Comment by nettrom** [comment]
For reference, 12 wikis in total were not in the dataset. One of those was the Cantonese Wiktionary, while the others are various committee and user group/affiliate wikis. If we keep using WikimediaMessages as our source, I think we'd also want to check regularly to get a sense of how often updates are needed both to our canonical dataset as well as WikimediaMessages.

**Comment by jenniferwang-wmf** [comment]
Since I just compared two versions of wikis.csv during the review, I documented the changes in this file for reference. 15 wikis in wikis.csv are updated with this pull. 12 wikis are added by fixing missing English names. 2 New wikis are added. 1 wiki is updated with english_name and domain_name.

**Comment by bearloga** [comment]
Thank you very much!
